feat: allow airplane mode control
mobile-dev-inc/maestro pull request #1672
Opened 2024-02-06 11:52 UTC by NyCodeGHG

## Proposed Changes

add a new command for controlling the airplane mode of android devices.

## Testing

ran the following flow on android 27 and 28 emulators:
```yaml
appId: org.wikipedia
---
- launchApp
- setAirplaneMode: disable
- setAirplaneMode: enable
```

2024-05-22 15:03 UTC, axelniklasson commented
@NyCodeGHG Nice 🎉 Let's update it to be a single command `- toggleAirplaneMode` instead and then we'll move forward with a formal review to get it merged. Thanks!

2024-05-23 07:34 UTC, axelniklasson requested changes
https://github.com/mobile-dev-inc/maestro/pull/1672#issuecomment-2125030154

2024-05-24 07:08 UTC, NyCodeGHG commented
@axelniklasson hi, thank you for the review.
When I implemented this feature I had another option to toggle the airplane mode, but I removed it as it doesn't explicitly define the desired behavior. 
I can add another option to toggle if you want, but I'd prefer to keep the enable and disable options for those who want to be explicit.

2024-05-24 08:47 UTC, axelniklasson commented
> @axelniklasson hi, thank you for the review. When I implemented this feature I had another option to toggle the airplane mode, but I removed it as it doesn't explicitly define the desired behavior. I can add another option to toggle if you want, but I'd prefer to keep the enable and disable options for those who want to be explicit.

Hey, that's fair and a good use case to me. Let's keep the API as it is but also add `- toggleAirplaneMode` as a separate command

2024-05-24 08:49 UTC, axelniklasson commented on maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
> +    @JsonProperty("enable")
```suggestion
    @JsonProperty("enabled")
```

2024-05-24 08:49 UTC, axelniklasson commented on maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
> +    @JsonProperty("disable")
```suggestion
    @JsonProperty("disabled")
```

2024-05-24 15:00 UTC, axelniklasson approved these changes
Nice, this works well for me! Can you also raise a PR in https://github.com/mobile-dev-inc/maestro-docs as well as adding another test case to the integration tests? Thanks!

2024-05-24 15:00 UTC, axelniklasson commented on maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
> +            AirplaneValue.Disable -> "Disable Airplane mode"
```suggestion
            AirplaneValue.Enable -> "Enable airplane mode"
            AirplaneValue.Disable -> "Disable airplane mode"
```

2024-05-27 10:46 UTC, NyCodeGHG commented
@axelniklasson 
I'm not sure on the integration test case
Can you elaborate?

2024-05-27 13:59 UTC, axelniklasson commented
Thanks @NyCodeGHG! Merging this now but please do also raise a PR in https://github.com/mobile-dev-inc/maestro-docs documenting the new commands - we'll merge it when we make the next release 👍 

Thanks again for your contribution!

2024-05-27 13:59 UTC, merged

2024-05-28 07:20 UTC, NyCodeGHG commented
will do!