Fetch, format and display changelog in the CLI update message
mobile-dev-inc/maestro pull request #1950
Opened 2024-08-25 19:55 UTC by tokou

## Proposed changes

- Fetch, the changelog from Github's `CHANGELOG.md`
- Filter the changes related to the proposed version
- Format them to be suitable for CLI display (remove links, bold and keep only top-level bullets)

## Testing

- Hardcoded some versions as proposed for update and built the project

### Latest version (patches)
```
╭───────────────────────────────────────────────────────────────────────────╮
│                                                                           │
│   A new version of the Maestro CLI is available (1.37.9).                 │
│                                                                           │
│   See what's new:                                                         │
│   https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#1379   │
│                                                                           │
│   - Revert iOS landscape mode fix (#1916)                                 │
│                                                                           │
│   Upgrade command:                                                        │
│   curl -Ls "https://get.maestro.mobile.dev" | bash                        │
│                                                                           │
╰───────────────────────────────────────────────────────────────────────────╯
```
### Big releases (minor versions)
```
╭───────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                               │
│   A new version of the Maestro CLI is available (1.37.0).                                     │
│                                                                                               │
│   See what's new:                                                                             │
│   https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#1370                       │
│                                                                                               │
│   - Sharding tests for parallel execution on many devices 🎉 (#1732 by Kaan)                  │
│   - Reports in HTML (#1750 by Depa Panjie Purnama)                                            │
│   - Homebrew is back!                                                                         │
│   - Current platform exposed in JavaScript (#1747 by Dan Caseley)                             │
│   - Control airplane mode (#1672 by NyCodeGHG)                                                │
│   - New `killApp` command (#1727 by Alexandre Favre)                                          │
│   - Fix cleaning up retries in iOS driver (#1669)                                             │
│   - Fix some commands not respecting custom labels (#1762 by Dan Caseley)                     │
│   - Fix “Protocol family unavailable” when rerunning iOS tests (#1671 by Stanisław Chmiela)   │
│                                                                                               │
│   Upgrade command:                                                                            │
│   curl -Ls "https://get.maestro.mobile.dev" | bash                                            │
│                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────╯
```
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                               │
│   A new version of the Maestro CLI is available (1.35.0).                                                                     │
│                                                                                                                               │
│   See what's new:                                                                                                             │
│   https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#1350                                                       │
│                                                                                                                               │
│   - Change: Adds view class to Android hierarchy output                                                                       │
│   - Change: Improves description of maestro start-device command to include device locale as well                             │
│   - Change: Adds scrollable attribute to Android view hierarchy output                                                        │
│   - Feature: Adds childOf attribute to selector to select from children of a container                                        │
│   - Feature: Adds label attribute to customize the CLI output of maestro commands                                             │
│   - Fix: Fixing “Unsupported architecture UNKNOWN” on linux environment when calling maestro attempts to create devices       │
│   - Fix: Allow maestro to work below API level 25 for Android                                                                 │
│   - Fix: IllegalArgumentException on swipe operation for iOS if the coordinates beyond device width and height are selected   │
│                                                                                                                               │
│   Upgrade command:                                                                                                            │
│   curl -Ls "https://get.maestro.mobile.dev" | bash                                                                            │
│                                                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                         │
│   A new version of the Maestro CLI is available (1.30.0).                                                                                               │
│                                                                                                                                                         │
│   See what's new:                                                                                                                                       │
│   https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#1300                                                                                 │
│                                                                                                                                                         │
│   - Feature: onFlowStart / onFlowComplete hooks                                                                                                         │
│   - Feature: Maestro Studio revamp                                                                                                                      │
│   - improved design                                                                                                                                     │
│   - search components panel                                                                                                                             │
│   - improved drag-and-drop                                                                                                                              │
│   - Feature: Introduce `--app-binary-id` parameter for  [...]

2024-08-27 14:02 UTC, bartekpacia requested changes
Thanks a taking a stab at this. Please check review comments.

2024-08-27 14:02 UTC, bartekpacia commented on maestro-cli/src/main/java/maestro/cli/update/Updates.kt
> +
I'd hesitant to merge this code. We'll have to be very careful with format of our changelog.

Could we [use CommonMark instead, and use its basic `TextContentRenderer`?](https://github.com/commonmark/commonmark-java?tab=readme-ov-file#render-to-markdown)

2024-08-31 04:54 UTC, tokou commented
I decided to write a custom Visitor rather than using `TextMarkdownRenderer`.
It makes a neater result. Here's the difference between both.

<details><summary>Using ChangelogVisitor</summary>
<pre>
1.38.1
  — New commands AI visual testing: assertWithAI and assertNoDefectsWithAI
  — Enable basic support for Maestro uploads while keeping maestro cloud functioning
1.37.9
  — Revert iOS landscape mode fix (#1916)
1.37.8
  — Fix sharding on Android failing on all but one devices (quick hotfix) (#1867)
  — Fix CLI crash when flow is canceled on Maestro Cloud (#1912)
  — Fix iOS landscape mode (caveats apply) (#1809)
  — Skip search engine selection when running on the web (#1869)
1.37.7
  — Fix cryptic "Socket Exception" when CI env var is set, once and for all (#1882)
1.37.6
  — Print stack trace on 3rd retry (#1877)
1.37.5
  — Fix cryptic "SocketException" when API token is invalid (#1871)
1.37.4
  — Don't ask for analytics permission on CI + add MAESTRO_CLI_NO_ANALYTICS env var (#1848)
1.37.3
  — Fix FileNotFoundException: ~.maestro/sessions (#1843)
1.37.2
  — Fix UnsupportedOperationException: Empty collection can't be reduced (#1840)
1.37.1
  — Fix crash when flutter or xcodebuild is not installed (#1839)
1.37.0
  — Sharding tests for parallel execution on many devices 🎉 (#1732 by Kaan)
  — Reports in HTML (#1750 by Depa Panjie Purnama)
  — Homebrew is back!
  — Current platform exposed in JavaScript (#1747 by Dan Caseley)
  — Control airplane mode (#1672 by NyCodeGHG)
  — New killApp command (#1727 by Alexandre Favre)
  — Fix cleaning up retries in iOS driver (#1669)
  — Fix some commands not respecting custom labels (#1762 by Dan Caseley)
  — Fix “Protocol family unavailable” when rerunning iOS tests (#1671 by Stanisław Chmiela)
1.36.0
  — Feature: Add support for extra keys to Android TV
  — Feature: Add support for pressing tab key on Android
  — Feature: Add status and time to report.xml
  — Fix: Extend retry to handle 404 in upload status call
  — Fix: Crashes caused by toasts on Android API < 30
1.35.0
  — Change: Adds view class to Android hierarchy output
  — Change: Improves description of maestro start-device command to include device locale as well
  — Change: Adds scrollable attribute to Android view hierarchy output
  — Feature: Adds childOf attribute to selector to select from children of a container
  — Feature: Adds label attribute to customize the CLI output of maestro commands
  — Fix: Fixing “Unsupported architecture UNKNOWN” on linux environment when calling maestro attempts to create devices
  — Fix: Allow maestro to work below API level 25 for Android
  — Fix: IllegalArgumentException on swipe operation for iOS if the coordinates beyond device width and height are selected
1.34.5
  — Feature: Adds a parameter to exclude all the keyboard elements from hierarchy
1.34.4
  — Fix: Failures due to swipe ranges going beyond screen dimensions
  — Change: Adding escape key in pressKey API
  — Tweak: Avoid returning Result in IOSDriver install and clearAppState
1.34.3
  — Tweak: Include scrollable attribute in view hierarchy from Android Driver
  — Feature: Custom labels for readability of maestro commands
  — Feature: Adding childOf selector
  — Tweak: Message of start-device command to show locale as well
1.34.2
  — Tweak: Include view class in view hierarchy attributes from the Android driver
1.34.1
  — Feature: add support --device-locale parameter for maestro cloud command
  — Feature: add support iOS17 for maestro start-device command
  — Feature: add support Android API level 34 for maestro start-device command
1.34.0
  — Feature: support --device-locale parameter for maestro start-device
  — Feature: add centerElement parameter for scrollUntilVisible. Center element will attempt to stop scrolling when the element is near the center of the screen.
  — Feature: add power button support for pressKey on Android
  — Change: add tapOn parameter waitToSettleTimeoutMs to control how long it waits to move on to the next command. Helpful for animation heavy apps.
  — Change: improve executionOrder planning
  — Change: improve retry mechanism to ensure openness of XCUITest Server
  — Fix: improve TimeoutException for driver startup
1.33.1
  — Feature: support for multipart form data file upload in Javascript, thanks @maciejkrolik
  — Fix: setPermissions produces error on Xcode 15
  — Fix: Maestro studio - include enter key in command editor on initial paste
1.33.0
  — Feature: Adds MAESTRO_DRIVER_STARTUP_TIMEOUT to iOS driver to configure timeout to start iOS driver, used in CI/CD environment with performance limitations. Thanks, Jesse Farsong for contributing.
  — Feature: Introducing the "addMedia" command that enables adding images and videos directly to the devices.
  — Change: Improved Studio's user interface:
  — Fix: Crash resulting in Error: No matches found for first query match sequence: Children matching type Other due to resolving root element for a snapshot operation on iOS
  — Fix: Android driver getting stuck when the device was disconnected
  — Fix: XCTestUnreachable exceptions due to missing IPv6 config on /etc/hosts
  — Fix: Handling app crash errors from XCUITest drivers gracefully
  — Fix: Timeouts can be separated with _. For example 10_000 for 10000
1.32.0
  — Feature: Support writing Flows using AI (more info to come 🚀)
  — Feature: Maestro Studio can now run in multiple tabs simultaneously
  — Feature: Added element id and copy option for it
  — Tweak: Hide action buttons till command is hovered
  — Tweak: Hide Unnecessary Scrollbars
  — Tweak: Repl view scroll improvements
  — Tweak: Improve Maestro Studio performance
  — Fix: Selected element size
  — Fix: Performance issues with maestro studio device refresh
  — Fix: Fixed dark mode for element id
  — Feature: New command to start or create a Maestro recommended device (docs)
  — Feature: Support id selection for testID with react-native-web (community contribution)
  — Feature: Control if browser automatically opens when running Maestro Studio via --no-window (community contribution)
  — Tweak: Show cancellation reason when available (Maestro Cloud)
  — Tweak: Update selenium-java and remove webdrivermanager to support Chrome 116+
  — Tweak: Show device type when running on Maestro Cloud
  — Tweak: Added better messaging and recovery options for Maestro Cloud uploads (useful for CI)
  — Tweak: Added better error messages for missing workspace and yaml validation errors
  — Tweak: Added file name and line number in yaml parsing error messages
  — Fix: Input text and erase text stability improvements for iOS
  — Fix: Leaking response body on iOS & better error handling for iOS Driver
  — Fix: Fixed Maestro Cloud wrong exit code when flow failed
  — Fix: Debug commands parsing would crash maestro
  — Fix: Cleaning up debug logs
1.31.0
  — Fix: Warning shown from OkHttp for leaking response bodies on CLI
  — Fix: Scroll for React native apps on screens with large view hierarchies on iOS
  — Fix: Showing more descriptive errors on flow file not found during maestro cloud command.
  — Fix: Input text characters being skipped or being appended later in the test on iOS
  — Fix: Crash in debug output generation when maestro flow contains "/"’
  — Fix: Resolved issue where tapping on the device in maestro studio produced inaccurate click locations due to incorrect coordinates. Now fixed for accurate device interaction
  — Fix: In Maestro Studio, the issue of window resizing causing devices to overflow off the screen has been resolved.
  — Feature: Add headers to HTTP response for API calls done with Maestro. Thanks, Jesse Willoughby! for this contribution.
  — Feature: Now it is possible to configure the path with the –debug-output option for debugging information that maestro dumps in the user directory by default.
  — Feature: Enhanced Maestro Studio with keyboard accessibility, streamlining navigation and facilitating the copy, run, and edit commands using the keyboar [...]

2024-09-02 22:58 UTC, bartekpacia commented
Thanks a ton, this is really great work.

As for the env var, let's show the difference between `$current` and `$latest` versions, always. I.e. eliminate `CHANGELOG_LAST_VERSION_ONLY`.

However I'm afraid about it from maintainability standpoint. `ChangelogVisitor.kt` is especially complex. I would really prefer to not have it checked-in the repo. On the other hand, the results are really great. If you wrote a 2 smoke tests for it, it'd be great.

2024-09-02 22:58 UTC, bartekpacia approved these changes

2024-09-03 13:35 UTC, bartekpacia commented
Ugh, another thing, and it's my bad – CommonMark is a pure Java lib, and long-term, we'd like to make Maestro not require JVM through Kotlin/Native.

2024-09-03 13:59 UTC, tokou commented
Well my previous solution did not require any lib 😏

2024-09-03 14:59 UTC, bartekpacia commented
Yeah, let's go with that first solution then.

2024-09-04 11:50 UTC, bartekpacia approved these changes
Stellar work, thanks a ton (and sorry for the CommonMark incident. At least it's in the commit history.)

2024-09-04 11:50 UTC, merged